### ISSUE TITLE
server error at install

### ISSUE THREAD

**Issue by transonly** [ozh/yourls-sqlite#2]
I'm using:
nginx version: nginx/1.6.2
yourls version: 1.7.1
PHP Version 5.6.29-0+deb8u1
Sqlite3

mysql IS NOT installed and i don't want that so there's no existing db and the config for that db i left untouched. That's ok?

Placed your files in the /user dir. 
Via the admin page i click install and a blank page gets returned with a 500 server error in the console.

**Comment by ozh** [comment]
Check what the error log says, it may give extra info. Also, add `define ('YOURLS_DEBUG', true);` to your config, see https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps#enable-debugging-mode

**Comment by transonly** [comment]
it start with this error:

    2017/01/02 20:26:44 [error] 666#0: *227 FastCGI sent in stderr: "PHP message: PHP Warning:  SQLSTATE[HY000] [14] unable to open database file in /var/www/html/YOURLS-1.7.1/includes/ezSQL/ez_sql_pdo.php on line 85
followed by:
    PHP message: PHP Warning:  Require $dsn and $user and $password to create a connection in /var/w$

And this is what i filled in:
    				function __construct($dsn='SQLite:/var/www/html/YOURLS-1.7.1/user/mydb.db', $user='user', $password='*******', $ssl=array())

**Comment by gloomy-ghost** [comment]
I got 500 upon installation as well, the logs are a little different though

```
2018/05/03 06:05:22 [error] 20508#20508: *1 FastCGI sent in stderr: "PHP message: PHP Warning:  could not find driver in /var/www/url/includes/ezSQL/ez_sql_pdo.php on line 85
PHP message: PHP Deprecated:  Function create_function() is deprecated in /var/www/url/user/db.php on line 31
PHP message: PHP Warning:  Require $dsn and $user and $password to create a connection in /var/www/url/includes/ezSQL/ez_sql_pdo.php on line 65
PHP message: PHP Warning:  could not find driver in /var/www/url/includes/ezSQL/ez_sql_pdo.php on line 85
PHP message: PHP Warning:  Require $dsn and $user and $password to create a connection in /var/www/url/includes/ezSQL/ez_sql_pdo.php on line 65
PHP message: PHP Warning:  could not find driver in /var/www/url/includes/ezSQL/ez_sql_pdo.php on line 85
PHP message: PHP Warning:  Require $dsn and $user and $password to create a connection in /var/www/url/includes/ezSQL/ez_sql_pdo.php on line 65
PHP message: PHP Warning:  could not find driver in /var/www/url/includes/ezSQL/ez_sql_pdo.php on line 85
PHP message: PHP Warning:  Require $dsn and $user and $password to create a connection in /var/www/url/includes/ezSQL/ez_sql_pdo.php on line 65
PHP message: PHP Warning:  could not find driver in /var/www/url/includes/ezSQL/ez_sql_pdo.php on line 85
PHP message: PHP Warning:  Require $dsn and $user and $password to create a connection in /var/www/url/includes/ezSQL/ez_sql_pdo.php on line 65
PHP message: PHP Warning:  could not find driver in /var/www/url/includes/ezSQL/ez_sql_pdo.php on line 85
PHP message: PHP Notice:  Undefined property: ezSQL_pdo_sqlite_YOURLS::$dbh in /var/www/url/user/ez_sql_pdo_sqlite_yourls.php on line 75
PHP message: PHP Fatal error:  Uncaught Error: Call to a member function quote() on null in /var/www/url/user/ez_sql_pdo_sqlite_yourls.php:75
Stack trace:
#0 /var/www/url/includes/functions-formatting.php(193): ezSQL_pdo_sqlite_YOURLS->escape('version')
#1 /var/www/url/includes/functions-formatting.php(172): yourls_escape_real('version')
```
